### ISSUE TITLE
mv not working in cyqgwin?

### ISSUE THREAD

**Issue by domsl** [codybuell/mit#6]
Hey there, I really like your mit script, it is really useful.

As far as I see, everything works fine except for moving todos from one date to the other:
````
$ t ls
1 test
--
TODO: 1 of 1 tasks shown


$ t mit mv 1 monday
sed: can't read 1 s/\(^([A-Z]\{1\}) \)\(.*$\)/\1{2015.06.28} \2/: No such file or directory
sed: can't read 1 s/{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}}/{2015.06.29}/: No such file or directory
TODO: MIT '' moved to Monday.


$ t mit
No MITs found.

$ t mit mon test number 2
2 {2015.06.29} test number 2
TODO: 2 added.

$ t mit
Monday:
  test number 2 (2)

$  t mit mv 2 monday
sed: can't read 2 s/{[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}}/{2015.06.29}/: No such file or directory
TODO: MIT 'test number 2' moved to Monday.

````

Maybe I am doing something stupid? (Like getting the order wrong?)

I'm using cygwin64 on Windows 7 and I would appreciate the help. :)

**Comment by codybuell** [comment]
Looks like there is an issue caused by the different versions of SED.  Will look into a more permanent solution but in the meantime you can edit the mit script changing lines 175, 181, 188 and 194 so that instead of `sed -i '' "blablabla` you have `sed -i "blablabla`.  Remove the single quotes immediately after the -i option on each of the lines.

**Comment by domsl** [comment]
Thank you! I would have never found that :)

This resolved the issue for "already MIT" tasks.
I also changed the line 161, 163, 166, 168 so the conversion form non MIt task to MIT task works as well. (As far as can I see.)
Line 210 probably needs to be changed as well. 

I would have never found that :)

**Comment by codybuell** [comment]
Just pushed up a new version that addressed some other issues you would run into with sed.  It is a bit of a slow script, should be refactored at some point or re-written in another language.

**Comment by domsl** [comment]
Thank you, works perfectly.

I starting to learn python and I already think about doing something like todo.txt cli (with dates) as a starting project. :)
