### ISSUE TITLE
converting 'non mits' to 'mits'

### ISSUE THREAD

**Issue by martynjy** [codybuell/mit#9]
I must be doing this wrong!
When trying to convert a 'non mit' using date format:
```
$ t ls
57 TEST @home
$ t mit mv 57 2017.07.10
TODO: MIT 'TEST @home' moved to Monday, July 10.
```
I get:
`57 {} TEST @home`

If I use day format:
```
$ t mit mv 57 monday 
TODO: MIT 'TEST @home' moved to Monday.
```
I get the correct entry:
`57 {2017.07.10} TEST @home`

**Comment by codybuell** [comment]
@martynjy nope, you're doing it right.  Will see if we can get this fixed here...
